export const siteConfig = {
  name: 'AWS Student Builder Group - KARE',
  shortName: 'AWS SBG KARE',
  description: 'A student-led community at Kalasalingam Academy of Research and Education empowering students with real-world AWS cloud skills through workshops, hackathons, certifications, and hands-on labs.',
  url: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
  ogImage: '/og-image.png',
  institution: {
    name: 'Kalasalingam Academy of Research and Education',
    shortName: 'KARE',
    location: 'Krishnan Kovil, Tamil Nadu, India',
  },
  social: {
    instagram: 'https://www.instagram.com/kare_aws.sbg/',
    linkedin: 'https://www.linkedin.com/company/kare-awscloudclub/',
    meetup: 'https://www.meetup.com/awscloudclub_kare/',
    github: '',
  },
  nav: {
    main: [
      { label: 'Home', href: '/' },
      { label: 'About', href: '/about' },
      { label: 'Events', href: '/events' },
      { label: 'Projects', href: '/projects' },
      { label: 'Team', href: '/team' },
      { label: 'Resources', href: '/resources' },
      { label: 'Community', href: '/community' },
    ],
    cta: { label: 'Join Us', href: '/join' },
    footer: [
      { label: 'Blog', href: '/blog' },
      { label: 'Gallery', href: '/gallery' },
      { label: 'Opportunities', href: '/opportunities' },
      { label: 'Contact', href: '/contact' },
    ],
    dashboard: [
      { label: 'Overview', href: '/dashboard' },
      { label: 'My Profile', href: '/dashboard/profile' },
      { label: 'My Events', href: '/dashboard/events' },
      { label: 'My Registrations', href: '/dashboard/registrations' },
      { label: 'My Projects', href: '/dashboard/projects' },
      { label: 'Certificates', href: '/dashboard/certificates' },
      { label: 'Achievements', href: '/dashboard/achievements' },
      { label: 'Opportunities', href: '/dashboard/opportunities' },
      { label: 'Saved Resources', href: '/dashboard/resources' },
      { label: 'Announcements', href: '/dashboard/announcements' },
      { label: 'Community', href: '/dashboard/community' },
    ],
    admin: [
      { label: 'Dashboard', href: '/admin' },
      { label: 'Events', href: '/admin/events' },
      { label: 'Registrations', href: '/admin/registrations' },
      { label: 'Members', href: '/admin/members' },
      { label: 'Team', href: '/admin/team' },
      { label: 'Projects', href: '/admin/projects' },
      { label: 'Resources', href: '/admin/resources' },
      { label: 'Blog', href: '/admin/blog' },
      { label: 'Gallery', href: '/admin/gallery' },
      { label: 'Opportunities', href: '/admin/opportunities' },
      { label: 'Announcements', href: '/admin/announcements' },
      { label: 'Certificates', href: '/admin/certificates' },
      { label: 'Analytics', href: '/admin/analytics' },
      { label: 'Settings', href: '/admin/settings' },
      { label: 'Audit Log', href: '/admin/audit-log' },
    ],
  },
  trademark: 'Amazon Web Services, AWS, and related marks are trademarks of Amazon.com, Inc. This student group is not affiliated with or endorsed by Amazon Web Services.',
} as const;
